# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Verdict
email: pyongjoo@umich.edu
description: > # this means to ignore newlines until "baseurl:"
    Verdict is a fast, resource-efficient data analytics system.
baseurl: "/verdict-site" # the subpath of your site, e.g. /blog
url: "http://dbgroup.eecs.umich.edu" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Project settings
version: 0.3.0
github_link: https://github.com/mozafari/verdict
verdict_core_jar: verdict-core-0.3.0-with-dependencies.jar
source_code_link: https://github.com/mozafari/verdict/releases/download/v0.2.2-beta/verdict-v0.2.2-beta.zip
spark_jar_name: verdict-spark-0.3.0.zip
spark_jar_link: https://github.com/mozafari/verdict/releases/download/v0.2.2-beta/verdict-v0.2.2-beta.zip
jdbc_jar_name: verdict-jdbc-0.3.0.zip
jdbc_jar_link: https://github.com/mozafari/verdict/releases/download/v0.2.2-beta/verdict-v0.2.2-beta.zip
