baseurl: ''
description: Verdict is a fast, resource-efficient data analytics system.
email: verdict-site@umich.edu
github_link: https://github.com/mozafari/verdict
github_username: jekyll
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
      start_line: 1
    span:
      line_numbers: false
markdown: kramdown
title: Verdict
twitter_username: jekyllrb
url: http://verdictdb.org/
verdict_command_line_zip_name: verdict-cli-0.4.0.zip
verdict_command_line_zip_url: https://sourceforge.net/projects/verdict/files/0.4/verdict-cli-0.4.0.zip/download
verdict_core_jar_name: verdict-spark-lib-0.4.0.jar
verdict_core_jar_url: https://sourceforge.net/projects/verdict/files/0.4/verdict-spark-lib-0.4.0.jar/download
verdict_jdbc:
  cdh5.11.1:
    family: CDH
    name: verdict-jdbc-cdh5.11.1-0.4.0.jar
    url: https://sourceforge.net/projects/verdict/files/0.4/verdict-jdbc-cdh5.11.1-0.4.0.jar/download
  redshift:
    family: Redshift
    name: verdict-jdbc-redshift-0.4.0.jar
    url: https://sourceforge.net/projects/verdict/files/0.4/verdict-jdbc-redshift-0.4.0.jar/download
verdict_shell:
  cdh5.11.1:
    family: CDH
    name: verdict-cli-cdh5.11.1-0.4.0.zip
    url: https://sourceforge.net/projects/verdict/files/0.4/verdict-cli-cdh5.11.1-0.4.0.zip/download
  redshift:
    family: Redshift
    name: verdict-cli-redshift-0.4.0.zip
    url: https://sourceforge.net/projects/verdict/files/0.4/verdict-cli-redshift-0.4.0.zip/download
version: 0.4.0
